# Site settings
title: My GitHub Portfolio
description: A minimalistic dark-themed portfolio page showcasing my GitHub stats and tech stack.
url: "https://wreckage0907.github.io"  # Replace with your actual GitHub Pages URL
baseurl: "/"

remote_theme: pages-themes/hacker@v0.2.0
 # add this line to the plugins list if you already have one

# Build settings
markdown: kramdown
highlighter: rouge

# Sass settings
sass:
  style: compressed

# Exclude files from the build
exclude:
  - README.md
  - LICENSE

# Navigation settings (optional)
nav:
  - Home: /

# Social links (optional)
social_links:
  - { name: "LinkedIn", icon: "linkedin", url: "https://linkedin.com/in/girish-raghav-m" }
  - { name: "GitHub", icon: "github", url: "https://github.com/wreckage0907" }



# Plugins (optional)
plugins:
  - jekyll-seo-tag  # For SEO optimizations
  - jekyll-feed 
  - jekyll-remote-theme # For RSS feed

